'use client'
import type { KitVariant } from './identity'
const KEY='worker.kits.v2',LEGACY_KEY='worker.kits.v1'
export type CollectionState='attempted'|'earned'|'mastered'
export type BuiltKit={seasonLabel:string;variant:KitVariant;firstBuiltOn:string;lastBuiltOn:string;bestParts:number;bestCategories:number;bestScore:number;fewestHints:number;times:number;state:CollectionState}
export type Collection=Record<string,BuiltKit>
export function kitKey(seasonLabel:string,variant:string):string{return `${seasonLabel}|${variant}`}
export function dnaUnlocked(row:BuiltKit|undefined):boolean{return Boolean(row&&row.state!=='attempted')}
function stateFor(categories:number):CollectionState{return categories>=8?'mastered':categories>=6?'earned':'attempted'}
export interface CollectionStore{readonly remote:boolean;read():Promise<Collection>;record(entry:{seasonLabel:string;variant:KitVariant;parts:number;score?:number;hintsUsed?:number}):Promise<void>;clear():Promise<void>}
function parse(raw:string|null):Collection{if(!raw)return{};try{const parsed:unknown=JSON.parse(raw);if(typeof parsed!=='object'||parsed===null)return{};const out:Collection={};for(const [key,value] of Object.entries(parsed as Record<string,unknown>)){const row=value as Partial<BuiltKit>;if(typeof row.seasonLabel!=='string')continue;const variant:KitVariant=row.variant==='away'||row.variant==='third'?row.variant:'home';const first=typeof row.firstBuiltOn==='string'?row.firstBuiltOn:'';const categories=typeof row.bestCategories==='number'?row.bestCategories:(typeof row.bestParts==='number'?row.bestParts:0);out[key]={seasonLabel:row.seasonLabel,variant,firstBuiltOn:first,lastBuiltOn:typeof row.lastBuiltOn==='string'?row.lastBuiltOn:first,bestParts:typeof row.bestParts==='number'?row.bestParts:Math.min(5,categories),bestCategories:categories,bestScore:typeof row.bestScore==='number'?row.bestScore:0,fewestHints:typeof row.fewestHints==='number'?row.fewestHints:99,times:typeof row.times==='number'?row.times:1,state:row.state??stateFor(categories)}}return out}catch{return{}}}
export class LocalCollectionStore implements CollectionStore{readonly remote=false;async read():Promise<Collection>{try{const current=window.localStorage.getItem(KEY);if(current)return parse(current);const legacy=parse(window.localStorage.getItem(LEGACY_KEY));if(Object.keys(legacy).length)window.localStorage.setItem(KEY,JSON.stringify(legacy));return legacy}catch{return{}}}async record(entry:{seasonLabel:string;variant:KitVariant;parts:number;score?:number;hintsUsed?:number}):Promise<void>{try{const current=await this.read(),key=kitKey(entry.seasonLabel,entry.variant),existing=current[key];const today=new Date().toISOString().slice(0,10),score=entry.score??0,categories=Math.max(0,Math.min(8,entry.parts)),legacyParts=categories>=7?5:Math.min(4,categories),hints=entry.hintsUsed??99;const bestCategories=Math.max(existing?.bestCategories??0,categories);const next:BuiltKit={seasonLabel:entry.seasonLabel,variant:entry.variant,firstBuiltOn:existing?.firstBuiltOn??today,lastBuiltOn:today,bestParts:Math.max(existing?.bestParts??0,legacyParts),bestCategories,bestScore:Math.max(existing?.bestScore??0,score),fewestHints:Math.min(existing?.fewestHints??99,hints),times:(existing?.times??0)+1,state:stateFor(bestCategories)};window.localStorage.setItem(KEY,JSON.stringify({...current,[key]:next}))}catch{}}async clear():Promise<void>{try{window.localStorage.removeItem(KEY);window.localStorage.removeItem(LEGACY_KEY)}catch{}}}
export function activeCollection():CollectionStore{return new LocalCollectionStore()}
